version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-football
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: football
      POSTGRES_USER: football_user
      POSTGRES_PASSWORD: football_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
