spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/football
    username: football_user
    password: football_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 8080
